### ISSUE TITLE
promising

### ISSUE THREAD

**Issue by exisz** [weagle08/sequelizejs-decorators#1]
Really I like this project and this should have been adopted by the official sequelize project. Current typescript support looks tedious and confusing.

**Comment by weagle08** [comment]
Point me to the confusing part and I can maybe simplify it. I'm open to suggestions for improvement. I created this because I liked the way [typeorm](https://typeorm.io/#/) uses attributes for defining tables, but [sequelize](http://docs.sequelizejs.com/) is far better than [typeorm](https://typeorm.io/#/) for performing queries when it comes to syntax.

**Comment by weagle08** [comment]
Closing but feel free to make improvement suggestions or discussion here
